# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_TpWonKLHISniA21wAXA42Vjh0GUgXLw
"""

import pandas as pd
df = pd.DataFrame({ 'Familiya' : ["Turg'unov", 'Tursunov','Eshboyev',"Yo'ldashev",'Muhammadaliyev','Mamatvaliyev','Abduxakimov','Azizibloyev',"Do'ltaboyev",'Komilova','Madaminjonov','Mamadaliyev' ,'Mirzahamidov',"Ne'matova",'Nurmuhammadov'     ],

                    'Ism' : [ 'Abdulbosit' ,'Muhammadqodir' ,'Ilhom', 'Husniddin','Abdullo','Dilshodbek','Xursandbek','Hojiakbar','Muhammadjon','Dinora','Baxtiyorjon','Zikrullo','Jaloliddin','Dildoraxon','Muhammad' ],

                    'Yoshi' : [   '18', '19' ,'19','19','19','19','19','19','19','19','19','19','19','19','19'],
                    'Kursi' : [     '2','2' ,'2' ,'2','2','2','2','2','2','2','2','2','2','2','2']

})
print(df)

df.to_excel('malumot3.xlsx', index=False, sheet_name='Sheet1' )